import Config

# Configure your database
config :deckex, Deckex.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  # Host port 5435 — 5432/5433/5434 belong to other projects on this machine.
  port: 5435,
  database: "deckex_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :deckex, DeckexWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Port 4005 — the owner's slot for this project.
  http: [ip: {127, 0, 0, 1}, port: 4005],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "0uXn5m8KPaQoBt73ZAVHh+i0gDIxwsrSTwO41gNTi0IMMB5OLxsIht1CS2+gA7Vy",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:deckex, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:deckex, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :deckex, DeckexWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/deckex_web/router\.ex$"E,
      ~r"lib/deckex_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :deckex, dev_routes: true

# The stock generator drops the timestamp and the metadata in dev. Both are
# wrong for this app.
#
# **The timestamp**, because a unit of work here is minutes long: a pipeline
# stage routinely runs for six, and a line with no time cannot be placed
# against the run whose timeline the owner is reading on screen.
#
# **The metadata**, because "which deck was that about?" is the question every
# line has to answer — the app runs three decks and every message would
# otherwise be anonymous. Only `deck` is printed, and it is printed as the
# NAME: the ids are carried for a structured backend, but on a terminal they
# are 36 characters of noise in front of the sentence you wanted to read.
config :logger, :default_formatter,
  format: "$time [$level] $metadata$message\n",
  metadata: [:deck]

# Dev shipped with no level at all, which means `:debug` — and `:debug` in this
# app is **every Ecto query, with its SQL and its params**. Measured 2026-08-27:
# one render of a deck page issues 56 queries and ~13,5 KB of log, and
# `web_console_logger: true` above sends the same stream to the browser console,
# so a session pays for it twice. Nothing is wrong with any single line; the
# volume is what fills a terminal's scrollback until the terminal stops
# answering, and a scrollback buffer is memory, not disk.
#
# `:info` keeps what a person actually reads while working — the request line,
# Oban's job results, and every warning and error this app writes on purpose.
# When a query IS the question, ask for it by name:
#
#     LOG_LEVEL=debug mix phx.server
requested_level = System.get_env("LOG_LEVEL", "info")

known_levels = ~w(emergency alert critical error warning notice info debug)

config :logger,
  level:
    if(requested_level in known_levels, do: String.to_existing_atom(requested_level), else: :info)

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
